namespace LitXusCount.Application.Settings.Products;

public record ProductDto(
    long Id,
    string Code,
    string? Code2,
    string? ParentProductCode,
    long? CategoryId,
    string? CategoryName,
    string? Description,
    
    long? SalesCogsAccountId,
    string? SalesCogsAccountName,
    long? SalesRevenueAccountId,
    string? SalesRevenueAccountName,
    long? PurchaseCostAccountId,
    string? PurchaseCostAccountName,
    long? PurchaseAccountId,
    string? PurchaseAccountName,
    
    string? SalesTaxCode,
    string? PurchaseTaxCode,
    long? DefaultSupplierId,
    string? DefaultSupplierName,
    long? MainUnitOfMeasureId,
    string? MainUnitOfMeasureName,
    long? AltUnitOfMeasureId,
    string? AltUnitOfMeasureName,
    decimal ConversionFactor,
    int ShelfLifeDays,
    
    decimal UnitCostPrice,
    decimal UnitSellingPrice,
    decimal UnitSellingPrice2,
    decimal MinSalesQty2,
    decimal UnitSellingPrice3,
    decimal MinSalesQty3,
    
    string? PromoCode,
    DateTime? PromoFromDate,
    DateTime? PromoToDate,
    
    decimal MinQty,
    decimal MaxQty,
    decimal ReorderQty,
    int LeadTimeDays,
    string? PackagingQty,
    string? Remark,
    string? ImageRef,
    bool IsActive);

public record ProductUpsertDto(
    string Code,
    string? Code2,
    string? ParentProductCode,
    long? CategoryId,
    string? Description,
    long? SalesCogsAccountId,
    long? SalesRevenueAccountId,
    long? PurchaseCostAccountId,
    long? PurchaseAccountId,
    string? SalesTaxCode,
    string? PurchaseTaxCode,
    long? DefaultSupplierId,
    long? MainUnitOfMeasureId,
    long? AltUnitOfMeasureId,
    decimal ConversionFactor,
    int ShelfLifeDays,
    decimal UnitCostPrice,
    decimal UnitSellingPrice,
    decimal UnitSellingPrice2,
    decimal MinSalesQty2,
    decimal UnitSellingPrice3,
    decimal MinSalesQty3,
    string? PromoCode,
    DateTime? PromoFromDate,
    DateTime? PromoToDate,
    decimal MinQty,
    decimal MaxQty,
    decimal ReorderQty,
    int LeadTimeDays,
    string? PackagingQty,
    string? Remark,
    string? ImageRef);
